cifar-10:
  model:
    in_channels: 3
    num_classes: 10
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4

cifar-100:
  model:
    in_channels: 3
    num_classes: 100
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4

stl-10:
  model:
    in_channels: 3
    num_classes: 10
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4

mini-imagenet:
  model:
    in_channels: 3
    num_classes: 100
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4

tiny-imagenet:
  model:
    in_channels: 3
    num_classes: 200
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4

mnist:
  model:
    in_channels: 1
    num_classes: 10
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4

fashion-mnist:
  model:
    in_channels: 1
    num_classes: 10
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4
